if (self.CavalryLogger) { CavalryLogger.start_js(["EKRZi"]); }

__d("FBOverlayElement.react",["cx","React","joinClasses","prop-types"],(function(a,b,c,d,e,f,g){__p&&__p();var h={horizontal:{left:"_32rg",right:"_32rh",fit:"_32rg _32rh",center:"_1cy5"},vertical:{top:"_32ri",bottom:"_32rj",fit:"_32ri _32rj",middle:"_1cy6"}};a=function(a){"use strict";babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}var d=c.prototype;d.render=function(){var a=b("React").Children.only(this.props.children),c=b("joinClasses")(a.props.className,"_32rk",h.horizontal[this.props.horizontal],h.vertical[this.props.vertical]);return b("React").cloneElement(a,{className:c})};return c}(b("React").PureComponent);a.propTypes={horizontal:b("prop-types").oneOf(["left","right","fit","center"]),vertical:b("prop-types").oneOf(["top","bottom","fit","middle"])};a.defaultProps={horizontal:"fit",vertical:"fit"};e.exports=a}),null);
__d("Clipboard",["Promise","UserAgent"],(function(a,b,c,d,e,f){__p&&__p();var g={isSupported:function(){return window.document.queryCommandSupported instanceof Function&&window.document.queryCommandSupported("copy")&&!(b("UserAgent").isBrowser("Firefox < 41")||b("UserAgent").isPlatform("iOS < 10.3"))||b("UserAgent").isBrowser("Chrome >= 43")},copy:function(a,c){__p&&__p();c=c||document.body;if(!c)return!1;var d=!0,e=document.createElement("textarea");c.appendChild(e);e.value=a;if(b("UserAgent").isPlatform("iOS >= 10.3")){a=document.createRange();a.selectNodeContents(e);var f=window.getSelection();f.removeAllRanges();f.addRange(a);e.setSelectionRange(0,999999)}else e.select();try{d=document.execCommand("copy")}catch(a){d=!1}c.removeChild(e);return d},copyAsync:function(a){var c=window.navigator;if(c&&c.clipboard&&typeof c.clipboard.writeText==="function")return c.clipboard.writeText(a);return g.copy(a)?b("Promise").resolve():b("Promise").reject()}};e.exports=g}),null);
__d("ColorUtils",[],(function(a,b,c,d,e,f){"use strict";__p&&__p();var g=new RegExp("^[#]{0,1}([\\w]{1,2})?([\\w]{1,2})([\\w]{1,2})([\\w]{1,2})$"),h=function(a,b){__p&&__p();if(a==null)return null;a=a.match(g);if(a==null)return null;a=a.slice(1).map(function(a){return parseInt(a.length==1?a+a:a,16)});if(a.length==4){b==="ARGB"&&a.push(a.shift());return"rgba("+a[0]+","+a[1]+","+a[2]+","+a[3]+")"}return"rgb("+a[0]+","+a[1]+","+a[2]+")"};a={hexARGBToCSSRGBA:function(a){return h(a,"ARGB")},hexRGBAToCSSRGBA:function(a){return h(a,"RGBA")}};e.exports=a}),null);
__d("useBoolean",["React"],(function(a,b,c,d,e,f){"use strict";__p&&__p();var g=b("React").useCallback,h=b("React").useState;function a(a){a=h(a);var b=a[0],c=a[1];return{value:b,set:c,toggle:g(function(){return c(function(a){return!a})},[]),setTrue:g(function(){return c(!0)},[]),setFalse:g(function(){return c(!1)},[])}}e.exports=a}),null);
__d("useResizeObserver",["FBLogger","React","ReactDOM","gkx","resize-observer-polyfill","uniqueID","useLayoutEffect_SAFE_FOR_SSR"],(function(a,b,c,d,e,f){"use strict";__p&&__p();var g=b("React").useCallback,h=b("React").useRef;function a(a){var c=h(null),d=h(a);b("useLayoutEffect_SAFE_FOR_SSR")(function(){d.current=a},[a]);return g(function(b){var a=function(a,b,c){d.current&&d.current(a,b,c)};b=b==null?null:n(b,a);c.current&&c.current();c.current=b},[])}var i=null,j=new Map();function k(){i==null&&(i=new(b("resize-observer-polyfill"))(m));return i}function l(a){return b("gkx")("1050822")?b("ReactDOM").unstable_batchedUpdates(a):a()}function m(a){__p&&__p();var c=new Map(a.map(function(a){return[a.target,a.contentRect]})),d=new Set(j.keys());l(function(){__p&&__p();for(var a=c,e=Array.isArray(a),f=0,a=e?a:a[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var g;if(e){if(f>=a.length)break;g=a[f++]}else{f=a.next();if(f.done)break;g=f.value}g=g;var h=g[0];g=g[1];var i=j.get(h);if(i!=null)for(var i=i,k=Array.isArray(i),l=0,i=k?i:i[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var m;if(k){if(l>=i.length)break;m=i[l++]}else{l=i.next();if(l.done)break;m=l.value}m=m;m=m[1];try{m(g,h,c)}catch(a){b("FBLogger")("useResizeObserver").catching(a)}}else d.has(h)||b("FBLogger")("useResizeObserver").mustfix("ResizeObserver observed resizing of an element that it should not be observing")}})}function n(a,c){var d,e=b("uniqueID")();d=(d=j.get(a))!=null?d:new Map();d.set(e,c);j.set(a,d);k().observe(a);return o(a,e)}function o(a,b){return function(){var c=j.get(a);if(c==null)return;c["delete"](b);c.size===0&&(k().unobserve(a),j["delete"](a))}}e.exports=a}),null);
__d("useContentRect",["React","useResizeObserver"],(function(a,b,c,d,e,f){"use strict";var g=b("React").useCallback,h=b("React").useState;function a(){var a=h(null),c=a[0],d=a[1];a=g(function(a){return d(a)},[]);a=b("useResizeObserver")(a);return[c,a]}e.exports=a}),null);
__d("useOnUpdateEffect",["React"],(function(a,b,c,d,e,f){"use strict";var g=b("React").useEffect,h=b("React").useRef;function a(a,b){var c=h(!1);g(function(){if(c.current===!0)return a();else c.current=!0},b)}e.exports=a}),null);
__d("ObserveResize.react",["useResizeObserver"],(function(a,b,c,d,e,f){"use strict";function a(a){var c=a.onResize;a=a.children;c=b("useResizeObserver")(c);return a(c)}e.exports=a}),null);
__d("useUniqueID",["React","uniqueID"],(function(a,b,c,d,e,f){"use strict";var g=b("React").useRef;function a(){var a=g(null);a.current===null&&(a.current=b("uniqueID")());return a.current}e.exports=a}),null);
__d("PECurrency",["PECurrencyConfig","intlNumUtils"],(function(a,b,c,d,e,f){"use strict";__p&&__p();var g=b("PECurrencyConfig").currency_map_for_cc,h=b("PECurrencyConfig").currency_map_for_render,i=100;function j(a){var b=0;a=a;while(a>1)b++,a/=10;return b}function k(a,b,c){var d=h[a].symbol,e=h[a].format||"{symbol}{amount}";c===!0&&d!=a&&(e.indexOf("{symbol}")>=e.indexOf("{amount}")?e+=" ("+a+") ":e+=" "+a);return e.replace("{symbol}",d).replace("{amount}",String(b))}function a(a,c,d){d=babelHelpers["extends"]({showCurrencyCode:!1,showDecimals:!0,showSymbol:!0,stripZeros:!1,thousandSeparator:!1},d);var e=o(a)||0;c=c/i;e=d.showDecimals?j(e):0;d.stripZeros||(c=b("intlNumUtils").formatNumber(c,e));d.thousandSeparator&&(typeof c==="string"&&(c=b("intlNumUtils").parseNumber(c)),c=b("intlNumUtils").formatNumberWithThousandDelimiters(Number(c),e));!d.showSymbol?e=d.showCurrencyCode?c+" "+a:String(c):(typeof c==="number"&&(c=""+c),e=k(a,c,d.showCurrencyCode));return e}function c(a,b,c,d,e){b=l(a,b,!0,c,d,e);switch(a){case"AUD":return"A"+b;case"CAD":return"C"+b;case"HKD":return"HK"+b;case"SGD":return"S"+b;case"COP":return"COP"+b;default:return b}}function l(a,c,d,e,f,g){__p&&__p();d=d!=null?d:!0;e=e!=null?e:!1;f=f!=null?f:!1;g=g!=null?g:!1;var h=o(a)||0,l=Math.abs(c)/i;h=j(h);f||(l=b("intlNumUtils").formatNumber(l,h));g&&(typeof l==="string"&&(l=b("intlNumUtils").parseNumber(l)),l=b("intlNumUtils").formatNumberWithThousandDelimiters(Number(l),f?0:h));!d?g=e?l+" "+a:String(l):(typeof l==="number"&&(l=""+l),g=k(a,l,e));c<0&&(g="-"+g);return g}function d(a,b,c,d,e){return l(a.currency,a.amount,b,c,d,e)}function f(a){a=p(a);return a!=null?Object.keys(a):[]}function m(a){return!h[a]?null:h[a].screen_name}function n(a){return!h[a]?null:h[a].symbol}function o(a){return!h[a]?null:h[a].offset}function p(a){switch(a){case 2:return g;case 1:return h;default:return null}}e.exports={DEFAULT_AMOUNT_OFFSET:i,formatAmount:l,formatAmountWithExtendedSymbol:c,formatAmountX:a,formatCurrencyAmount:d,formatRawAmount:k,getAllCurrencies:f,getCurrencyScreenName:m,getCurrencySymbol:n,getCurrencyOffset:o}}),null);
__d("InstantGamesPresenceProperties",[],(function(a,b,c,d,e,f){"use strict";__p&&__p();a=function(){__p&&__p();function a(){this.$1=!1}var b=a.prototype;b.addInstantGamePresence=function(){this.$1=!0};b.removeInstantGamePresence=function(){this.$1=!1};b.isActiveGamePresence=function(){return this.$1};return a}();b=new a();e.exports=b}),null);
__d("randomShuffle",["randomInt"],(function(a,b,c,d,e,f){__p&&__p();function a(a){for(var c=a.length-1;c>0;c--){var d=b("randomInt").call(this,c+1);if(d!=c){var e=a[d];a[d]=a[c];a[c]=e}}return a}e.exports=a}),null);
/**
 * License: https://www.facebook.com/legal/license/V9vdYColc4k/
 */
__d("react-dom-0.0.0",["ReactDOM"],(function(a,b,c,d,e,f){"use strict";__p&&__p();function a(a){return a&&typeof a==="object"&&"default"in a?a["default"]:a}var g=a(b("ReactDOM"));c={};var h={exports:c};function i(){h.exports=g}var j=!1,k=function(){j||(j=!0,i());return h.exports};d=function(a){switch(a){case void 0:return k()}};e.exports=d}),null);